// DOT Level Descriptions for Attributes and Abilities
// Format: 'dot.{name}.{level}': 'Description'

export const DOT_DESCRIPTIONS_EN = {
    // ATTRIBUTES - Physical
    'dot.strength.1': '• Poor: You can lift 40 lbs.',
    'dot.strength.2': '•• Average: You can lift 100 lbs.',
    'dot.strength.3': '••• Good: You can lift 250 lbs.',
    'dot.strength.4': '•••• Exceptional: You can lift 400 lbs.',
    'dot.strength.5': '••••• Outstanding: You can lift 650 lbs.',

    'dot.dexterity.1': '• Poor: You are clumsy and awkward.',
    'dot.dexterity.2': '•• Average: You have normal coordination.',
    'dot.dexterity.3': '••• Good: You have excellent hand-eye coordination.',
    'dot.dexterity.4': '•••• Exceptional: You could be a professional athlete or acrobat.',
    'dot.dexterity.5': '••••• Outstanding: Your movements are liquid grace.',

    'dot.stamina.1': '• Poor: You bruise easily and tire quickly.',
    'dot.stamina.2': '•• Average: You are moderately healthy.',
    'dot.stamina.3': '••• Good: You are in good shape and rarely get sick.',
    'dot.stamina.4': '•••• Exceptional: You can run marathons with ease.',
    'dot.stamina.5': '••••• Outstanding: Your constitution is truly legendary.',

    // ATTRIBUTES - Social
    'dot.charisma.1': '• Poor: You are not particularly captivating. Your presence is common and you have difficulty standing out in a crowd.',
    'dot.charisma.2': '•• Average: You are a common and sociable person, able to interact normally with others.',
    'dot.charisma.3': '••• Good: You are a pleasant and inspiring person. People enjoy being around you.',
    'dot.charisma.4': '•••• Exceptional: You have incredible personal magnetism. You lead naturally and inspire loyalty.',
    'dot.charisma.5': '••••• Outstanding: You possess supernatural charisma. Masses follow you and people would do anything for you.',

    'dot.manipulation.1': '• Poor: You are blunt and straightforward, often to your detriment.',
    'dot.manipulation.2': '•• Average: You can tell the occasional white lie.',
    'dot.manipulation.3': '••• Good: You could be a successful politician or con artist.',
    'dot.manipulation.4': '•••• Exceptional: You could be a cult leader or master manipulator.',
    'dot.manipulation.5': '••••• Outstanding: You can make anyone believe anything.',

    'dot.appearance.1': '• Poor: You are ugly or disfigured. People avoid looking at you.',
    'dot.appearance.2': '•• Average: You are plain and unremarkable.',
    'dot.appearance.3': '••• Good: You are attractive and turn heads.',
    'dot.appearance.4': '•••• Exceptional: You are stunning. People stop and stare.',
    'dot.appearance.5': '••••• Outstanding: You are breathtakingly beautiful, like a work of art.',

    // ATTRIBUTES - Mental
    'dot.perception.1': '• Poor: You are oblivious to your surroundings.',
    'dot.perception.2': '•• Average: You notice obvious things.',
    'dot.perception.3': '••• Good: You are alert and aware of subtle details.',
    'dot.perception.4': '•••• Exceptional: Very little escapes your notice.',
    'dot.perception.5': '••••• Outstanding: You instantly notice everything around you.',

    'dot.intelligence.1': '• Poor: You are slow to learn and understand. IQ 80.',
    'dot.intelligence.2': '•• Average: You are of average intelligence. IQ 100.',
    'dot.intelligence.3': '••• Good: You are bright and quick to learn. IQ 120.',
    'dot.intelligence.4': '•••• Exceptional: You are brilliant, a true intellectual. IQ 140.',
    'dot.intelligence.5': '••••• Outstanding: You are a genius of legendary proportions. IQ 160+.',

    'dot.wits.1': '• Poor: You are slow to react and easily confused.',
    'dot.wits.2': '•• Average: You can think on your feet when needed.',
    'dot.wits.3': '••• Good: You are quick-witted and rarely caught off guard.',
    'dot.wits.4': '•••• Exceptional: You always have a clever comeback or solution.',
    'dot.wits.5': '••••• Outstanding: Your mental reflexes are lightning-fast.',

    // TALENTS
    'dot.alertness.1': '• Novice: You notice obvious threats.',
    'dot.alertness.2': '•• Practiced: You are aware of your surroundings.',
    'dot.alertness.3': '••• Competent: Very little catches you by surprise.',
    'dot.alertness.4': '•••• Expert: You have a sixth sense for danger.',
    'dot.alertness.5': '••••• Master: Nothing escapes your notice.',

    'dot.athletics.1': '• Novice: You can jog and throw a ball.',
    'dot.athletics.2': '•• Practiced: You were on a high school sports team.',
    'dot.athletics.3': '••• Competent: You could compete in regional tournaments.',
    'dot.athletics.4': '•••• Expert: You could compete in national tournaments.',
    'dot.athletics.5': '••••• Master: Olympic-level athlete.',

    'dot.brawl.1': '• Novice: You can throw a punch.',
    'dot.brawl.2': '•• Practiced: You have been in a few fights.',
    'dot.brawl.3': '••• Competent: You could work as a bouncer.',
    'dot.brawl.4': '•••• Expert: You are a skilled martial artist.',
    'dot.brawl.5': '••••• Master: Legendary fighter.',

    'dot.dodge.1': '• Novice: You can duck.',
    'dot.dodge.2': '•• Practiced: You can avoid most attacks.',
    'dot.dodge.3': '••• Competent: You are hard to hit.',
    'dot.dodge.4': '•••• Expert: You move like water.',
    'dot.dodge.5': '••••• Master: Nearly impossible to strike.',

    'dot.empathy.1': '• Novice: You can tell when someone is upset.',
    'dot.empathy.2': '•• Practiced: You can read basic emotions.',
    'dot.empathy.3': '••• Competent: You understand people\'s motivations.',
    'dot.empathy.4': '•••• Expert: You can sense hidden feelings.',
    'dot.empathy.5': '••••• Master: You know what people will do before they do.',

    'dot.expression.1': '• Novice: You can get your point across.',
    'dot.expression.2': '•• Practiced: You are an engaging speaker.',
    'dot.expression.3': '••• Competent: You could be a professional performer.',
    'dot.expression.4': '•••• Expert: You captivate audiences.',
    'dot.expression.5': '••••• Master: Legendary performer or orator.',

    'dot.intimidation.1': '• Novice: You can be threatening when needed.',
    'dot.intimidation.2': '•• Practiced: People take you seriously.',
    'dot.intimidation.3': '••• Competent: You are genuinely frightening.',
    'dot.intimidation.4': '•••• Expert: You can break people with a look.',
    'dot.intimidation.5': '••••• Master: Your presence terrifies.',

    'dot.leadership.1': '• Novice: You can organize a small group.',
    'dot.leadership.2': '•• Practiced: People listen to your suggestions.',
    'dot.leadership.3': '••• Competent: You are a natural leader.',
    'dot.leadership.4': '•••• Expert: You inspire loyalty and devotion.',
    'dot.leadership.5': '••••• Master: People would die for you.',

    'dot.streetwise.1': '• Novice: You know how to avoid bad neighborhoods.',
    'dot.streetwise.2': '•• Practiced: You can navigate the urban underworld.',
    'dot.streetwise.3': '••• Competent: You have contacts in the criminal world.',
    'dot.streetwise.4': '•••• Expert: You know all the players and their games.',
    'dot.streetwise.5': '••••• Master: The streets are your domain.',

    'dot.subterfuge.1': '• Novice: You can tell white lies.',
    'dot.subterfuge.2': '•• Practiced: You can maintain a cover story.',
    'dot.subterfuge.3': '••• Competent: You are a skilled liar and manipulator.',
    'dot.subterfuge.4': '•••• Expert: You can fool almost anyone.',
    'dot.subterfuge.5': '••••• Master: Your lies become truth.',

    // SKILLS
    'dot.animalken.1': '• Novice: You can pet a dog.',
    'dot.animalken.2': '•• Practiced: You can train simple animals.',
    'dot.animalken.3': '••• Competent: You have a way with all animals.',
    'dot.animalken.4': '•••• Expert: Animals trust you instinctively.',
    'dot.animalken.5': '••••• Master: You are one with the beasts.',

    'dot.crafts.1': '• Novice: You can do basic repairs.',
    'dot.crafts.2': '•• Practiced: You can create simple items.',
    'dot.crafts.3': '••• Competent: You are a skilled craftsman.',
    'dot.crafts.4': '•••• Expert: Your work is of professional quality.',
    'dot.crafts.5': '••••• Master: You create masterpieces.',

    'dot.drive.1': '• Novice: You have a license.',
    'dot.drive.2': '•• Practiced: You can drive in difficult conditions.',
    'dot.drive.3': '••• Competent: You can perform evasive maneuvers.',
    'dot.drive.4': '•••• Expert: You could be a stunt driver.',
    'dot.drive.5': '••••• Master: You are one with the vehicle.',

    'dot.etiquette.1': '• Novice: You know basic manners.',
    'dot.etiquette.2': '•• Practiced: You can navigate social situations.',
    'dot.etiquette.3': '••• Competent: You know all the social graces.',
    'dot.etiquette.4': '•••• Expert: You are a master of protocol.',
    'dot.etiquette.5': '••••• Master: You set the standard for society.',

    'dot.firearms.1': '• Novice: You can shoot a gun.',
    'dot.firearms.2': '•• Practiced: You can hit a target reliably.',
    'dot.firearms.3': '••• Competent: You are a skilled marksman.',
    'dot.firearms.4': '•••• Expert: You rarely miss.',
    'dot.firearms.5': '••••• Master: Legendary sharpshooter.',

    'dot.melee.1': '• Novice: You can swing a weapon.',
    'dot.melee.2': '•• Practiced: You know how to use weapons in combat.',
    'dot.melee.3': '••• Competent: You are skilled with melee weapons.',
    'dot.melee.4': '•••• Expert: You are a weapon master.',
    'dot.melee.5': '••••• Master: Legendary warrior.',

    'dot.performance.1': '• Novice: You can carry a tune.',
    'dot.performance.2': '•• Practiced: You could perform at local venues.',
    'dot.performance.3': '••• Competent: You are a professional performer.',
    'dot.performance.4': '•••• Expert: You are famous in your field.',
    'dot.performance.5': '••••• Master: Legendary artist.',

    'dot.security.1': '• Novice: You can pick a simple lock.',
    'dot.security.2': '•• Practiced: You can bypass basic security.',
    'dot.security.3': '••• Competent: You can crack most systems.',
    'dot.security.4': '•••• Expert: Few systems can stop you.',
    'dot.security.5': '••••• Master: No lock can hold you.',

    'dot.stealth.1': '• Novice: You can hide in shadows.',
    'dot.stealth.2': '•• Practiced: You can move quietly.',
    'dot.stealth.3': '••• Competent: You are very hard to detect.',
    'dot.stealth.4': '•••• Expert: You are a ghost.',
    'dot.stealth.5': '••••• Master: You are invisible.',

    'dot.survival.1': '• Novice: You can camp.',
    'dot.survival.2': '•• Practiced: You can survive in the wilderness.',
    'dot.survival.3': '••• Competent: You thrive in nature.',
    'dot.survival.4': '•••• Expert: You are at home in the wild.',
    'dot.survival.5': '••••• Master: Nature bends to your will.',

    // KNOWLEDGES
    'dot.academics.1': '• Novice: High school education.',
    'dot.academics.2': '•• Practiced: College level.',
    'dot.academics.3': '••• Competent: Master\'s degree.',
    'dot.academics.4': '•••• Expert: Doctorate level.',
    'dot.academics.5': '••••• Master: World-renowned scholar.',

    'dot.computer.1': '• Novice: You can use email and browse the web.',
    'dot.computer.2': '•• Practiced: You can troubleshoot problems.',
    'dot.computer.3': '••• Competent: You are a skilled programmer.',
    'dot.computer.4': '•••• Expert: You are a hacking expert.',
    'dot.computer.5': '••••• Master: You are a digital god.',

    'dot.finance.1': '• Novice: You can balance a checkbook.',
    'dot.finance.2': '•• Practiced: You understand investments.',
    'dot.finance.3': '••• Competent: You could work on Wall Street.',
    'dot.finance.4': '•••• Expert: You manipulate markets.',
    'dot.finance.5': '••••• Master: You control economies.',

    'dot.investigation.1': '• Novice: You can find obvious clues.',
    'dot.investigation.2': '•• Practiced: You can piece together evidence.',
    'dot.investigation.3': '••• Competent: You are a skilled detective.',
    'dot.investigation.4': '•••• Expert: You solve the unsolvable.',
    'dot.investigation.5': '••••• Master: Nothing stays hidden from you.',

    'dot.law.1': '• Novice: You know your basic rights.',
    'dot.law.2': '•• Practiced: You understand legal procedures.',
    'dot.law.3': '••• Competent: You could practice law.',
    'dot.law.4': '•••• Expert: You are a legal expert.',
    'dot.law.5': '••••• Master: You shape the law itself.',

    'dot.linguistics.1': '• Novice: You speak one additional language.',
    'dot.linguistics.2': '•• Practiced: You speak two additional languages.',
    'dot.linguistics.3': '••• Competent: You speak four additional languages.',
    'dot.linguistics.4': '•••• Expert: You speak eight additional languages.',
    'dot.linguistics.5': '••••• Master: You can learn any language quickly.',

    'dot.medicine.1': '• Novice: You know first aid.',
    'dot.medicine.2': '•• Practiced: You could be a nurse.',
    'dot.medicine.3': '••• Competent: You are a practicing doctor.',
    'dot.medicine.4': '•••• Expert: You are a renowned surgeon.',
    'dot.medicine.5': '••••• Master: You perform medical miracles.',

    'dot.occult.1': '• Novice: You know basic superstitions.',
    'dot.occult.2': '•• Practiced: You understand occult traditions.',
    'dot.occult.3': '••• Competent: You are well-versed in the supernatural.',
    'dot.occult.4': '•••• Expert: You are an occult scholar.',
    'dot.occult.5': '••••• Master: You know the deepest mysteries.',

    'dot.politics.1': '• Novice: You follow the news.',
    'dot.politics.2': '•• Practiced: You understand political systems.',
    'dot.politics.3': '••• Competent: You are politically connected.',
    'dot.politics.4': '•••• Expert: You are a political power broker.',
    'dot.politics.5': '••••• Master: You control governments.',

    'dot.science.1': '• Novice: High school science.',
    'dot.science.2': '•• Practiced: College level.',
    'dot.science.3': '••• Competent: You are a professional scientist.',
    'dot.science.4': '•••• Expert: You make breakthrough discoveries.',
    'dot.science.5': '••••• Master: You redefine science itself.',

    // WILLPOWER (1-10)
    'dot.willpower.1': '• Spineless: You have no resolve.',
    'dot.willpower.2': '•• Weak: You are easily swayed.',
    'dot.willpower.3': '••• Unassertive: You prefer to follow than lead.',
    'dot.willpower.4': '•••• Diffident: You doubt your own strength.',
    'dot.willpower.5': '••••• Certain: You have a solid sense of self.',
    'dot.willpower.6': '•••••• Confident: You trust your own judgment.',
    'dot.willpower.7': '••••••• Determined: You rarely back down from a challenge.',
    'dot.willpower.8': '•••••••• Controlled: You have great mastery over your emotions.',
    'dot.willpower.9': '••••••••• Iron-willed: Your resolve is legendary.',
    'dot.willpower.10': '•••••••••• Unshakeable: Your mind is a fortress.',

    // HUMANITY (1-10)
    'dot.humanity.1': '• Monstrous: You are a beast in human shape.',
    'dot.humanity.2': '•• Bestial: You have very little regard for life.',
    'dot.humanity.3': '••• Cold: You are detached from human emotions.',
    'dot.humanity.4': '•••• Unfeeling: You are starting to lose your grip on morality.',
    'dot.humanity.5': '••••• Distant: You still remember what it is to be human.',
    'dot.humanity.6': '•••••• Decent: You try to avoid unnecessary harm.',
    'dot.humanity.7': '••••••• Normal: Most humans share this level of morality.',
    'dot.humanity.8': '•••••••• Caring: You value all life highly.',
    'dot.humanity.9': '••••••••• Compassionate: You are exceptionally moral.',
    'dot.humanity.10': '•••••••••• Saintly: You are a paragon of virtue.',

    // BLOOD POOL (1-10)
    'dot.blood_pool.1': '• Sated: You have almost no blood. Hunger is gnawing.',
    'dot.blood_pool.2': '•• Hungry: Your beast is restless.',
    'dot.blood_pool.3': '••• Peckish: You need to feed soon.',
    'dot.blood_pool.4': '•••• Neutral: You can function normally.',
    'dot.blood_pool.5': '••••• Sufficient: You have enough blood for minor tasks.',
    'dot.blood_pool.6': '•••••• Satisfied: You feel energized.',
    'dot.blood_pool.7': '••••••• Full: You are well-fed.',
    'dot.blood_pool.8': '•••••••• Stuffed: You have an abundance of vitae.',
    'dot.blood_pool.9': '••••••••• Overflowing: You are pulsing with power.',
    'dot.blood_pool.10': '•••••••••• Bursting: You are at maximum capacity for your generation.',

    // DISCIPLINE LEVELS (GENERIC)
    'dot.discipline.1': '• Level 1 Mastery',
    'dot.discipline.2': '•• Level 2 Mastery',
    'dot.discipline.3': '••• Level 3 Mastery',
    'dot.discipline.4': '•••• Level 4 Mastery',
    'dot.discipline.5': '••••• Level 5 Mastery',
};

export const DOT_DESCRIPTIONS_PT = {
    // ATRIBUTOS - Físicos
    'dot.strength.1': '• Fraco: Você pode levantar 18 kg.',
    'dot.strength.2': '•• Médio: Você pode levantar 45 kg.',
    'dot.strength.3': '••• Bom: Você pode levantar 115 kg.',
    'dot.strength.4': '•••• Excepcional: Você pode levantar 180 kg.',
    'dot.strength.5': '••••• Extraordinário: Você pode levantar 295 kg.',

    'dot.dexterity.1': '• Fraco: Você é desajeitado e sem coordenação.',
    'dot.dexterity.2': '•• Médio: Você tem coordenação normal.',
    'dot.dexterity.3': '••• Bom: Você tem excelente coordenação motora.',
    'dot.dexterity.4': '•••• Excepcional: Você poderia ser um atleta ou acrobata profissional.',
    'dot.dexterity.5': '••••• Extraordinário: Seus movimentos são de graça líquida.',

    'dot.stamina.1': '• Fraco: Você se machuca facilmente e cansa rápido.',
    'dot.stamina.2': '•• Médio: Você é moderadamente saudável.',
    'dot.stamina.3': '••• Bom: Você está em boa forma e raramente fica doente.',
    'dot.stamina.4': '•••• Excepcional: Você pode correr maratonas com facilidade.',
    'dot.stamina.5': '••••• Extraordinário: Sua constituição é verdadeiramente lendária.',

    // ATRIBUTOS - Sociais
    'dot.charisma.1': '• Medíocre: Você não é particularmente cativante. Sua presença é comum e você tem dificuldade em se destacar em uma multidão.',
    'dot.charisma.2': '•• Normal/Médio: Você é uma pessoa comum e sociável, capaz de interagir normalmente com os outros.',
    'dot.charisma.3': '••• Bom: Você é uma pessoa agradável e inspiradora. As pessoas gostam de estar perto de você.',
    'dot.charisma.4': '•••• Excepcional: Você tem um magnetismo pessoal incrível. Você lidera naturalmente e inspira lealdade.',
    'dot.charisma.5': '••••• Lendário: Você possui um carisma sobrenatural. As massas te seguem e as pessoas fariam qualquer coisa por você.',

    'dot.manipulation.1': '• Fraco: Você é direto e franco, muitas vezes para seu próprio prejuízo.',
    'dot.manipulation.2': '•• Médio: Você pode contar uma mentirinha ocasional.',
    'dot.manipulation.3': '••• Bom: Você poderia ser um político ou vigarista de sucesso.',
    'dot.manipulation.4': '•••• Excepcional: Você poderia ser um líder de culto ou mestre manipulador.',
    'dot.manipulation.5': '••••• Extraordinário: Você pode fazer qualquer um acreditar em qualquer coisa.',

    'dot.appearance.1': '• Feio: Você é feio ou desfigurado. As pessoas evitam olhar para você.',
    'dot.appearance.2': '•• Médio: Você é comum e sem destaque.',
    'dot.appearance.3': '••• Bom: Você é atraente e chama atenção.',
    'dot.appearance.4': '•••• Excepcional: Você é deslumbrante. As pessoas param e olham.',
    'dot.appearance.5': '••••• Extraordinário: Você é de tirar o fôlego, como uma obra de arte.',

    // ATRIBUTOS - Mentais
    'dot.perception.1': '• Fraco: Você é alheio ao seu redor.',
    'dot.perception.2': '•• Médio: Você nota coisas óbvias.',
    'dot.perception.3': '••• Bom: Você é alerta e percebe detalhes sutis.',
    'dot.perception.4': '•••• Excepcional: Muito pouco escapa à sua atenção.',
    'dot.perception.5': '••••• Extraordinário: Você nota instantaneamente tudo ao seu redor.',

    'dot.intelligence.1': '• Fraco: Você é lento para aprender e entender. QI 80.',
    'dot.intelligence.2': '•• Médio: Você tem inteligência média. QI 100.',
    'dot.intelligence.3': '••• Bom: Você é brilhante e aprende rápido. QI 120.',
    'dot.intelligence.4': '•••• Excepcional: Você é genial, um verdadeiro intelectual. QI 140.',
    'dot.intelligence.5': '••••• Extraordinário: Você é um gênio de proporções lendárias. QI 160+.',

    'dot.wits.1': '• Fraco: Você é lento para reagir e facilmente confuso.',
    'dot.wits.2': '•• Médio: Você consegue pensar rapidamente quando necessário.',
    'dot.wits.3': '••• Bom: Você é perspicaz e raramente é pego desprevenido.',
    'dot.wits.4': '•••• Excepcional: Você sempre tem uma resposta esperta ou solução.',
    'dot.wits.5': '••••• Extraordinário: Seus reflexos mentais são rápidos como um raio.',

    // TALENTOS
    'dot.alertness.1': '• Novato: Você nota ameaças óbvias.',
    'dot.alertness.2': '•• Praticante: Você está ciente do seu entorno.',
    'dot.alertness.3': '••• Competente: Muito pouco te pega de surpresa.',
    'dot.alertness.4': '•••• Especialista: Você tem um sexto sentido para perigo.',
    'dot.alertness.5': '••••• Mestre: Nada escapa à sua atenção.',

    'dot.athletics.1': '• Novato: Você pode correr e jogar uma bola.',
    'dot.athletics.2': '•• Praticante: Você jogou em times escolares.',
    'dot.athletics.3': '••• Competente: Você poderia competir em torneios regionais.',
    'dot.athletics.4': '•••• Especialista: Você poderia competir em torneios nacionais.',
    'dot.athletics.5': '••••• Mestre: Atleta de nível olímpico.',

    'dot.brawl.1': '• Novato: Você pode dar um soco.',
    'dot.brawl.2': '•• Praticante: Você já esteve em algumas brigas.',
    'dot.brawl.3': '••• Competente: Você poderia trabalhar como segurança.',
    'dot.brawl.4': '•••• Especialista: Você é um artista marcial habilidoso.',
    'dot.brawl.5': '••••• Mestre: Lutador lendário.',

    'dot.dodge.1': '• Novato: Você pode se abaixar.',
    'dot.dodge.2': '•• Praticante: Você pode evitar a maioria dos ataques.',
    'dot.dodge.3': '••• Competente: Você é difícil de acertar.',
    'dot.dodge.4': '•••• Especialista: Você se move como água.',
    'dot.dodge.5': '••••• Mestre: Quase impossível de atingir.',

    'dot.empathy.1': '• Novato: Você pode dizer quando alguém está chateado.',
    'dot.empathy.2': '•• Praticante: Você pode ler emoções básicas.',
    'dot.empathy.3': '••• Competente: Você entende as motivações das pessoas.',
    'dot.empathy.4': '•••• Especialista: Você pode sentir sentimentos ocultos.',
    'dot.empathy.5': '••••• Mestre: Você sabe o que as pessoas farão antes delas.',

    'dot.expression.1': '• Novato: Você consegue se expressar.',
    'dot.expression.2': '•• Praticante: Você é um orador envolvente.',
    'dot.expression.3': '••• Competente: Você poderia ser um artista profissional.',
    'dot.expression.4': '•••• Especialista: Você cativa audiências.',
    'dot.expression.5': '••••• Mestre: Artista ou orador lendário.',

    'dot.intimidation.1': '• Novato: Você pode ser ameaçador quando necessário.',
    'dot.intimidation.2': '•• Praticante: As pessoas te levam a sério.',
    'dot.intimidation.3': '••• Competente: Você é genuinamente assustador.',
    'dot.intimidation.4': '•••• Especialista: Você pode quebrar pessoas com um olhar.',
    'dot.intimidation.5': '••••• Mestre: Sua presença aterroriza.',

    'dot.leadership.1': '• Novato: Você pode organizar um pequeno grupo.',
    'dot.leadership.2': '•• Praticante: As pessoas ouvem suas sugestões.',
    'dot.leadership.3': '••• Competente: Você é um líder natural.',
    'dot.leadership.4': '•••• Especialista: Você inspira lealdade e devoção.',
    'dot.leadership.5': '••••• Mestre: As pessoas morreriam por você.',

    'dot.streetwise.1': '• Novato: Você sabe evitar bairros perigosos.',
    'dot.streetwise.2': '•• Praticante: Você pode navegar pelo submundo urbano.',
    'dot.streetwise.3': '••• Competente: Você tem contatos no mundo do crime.',
    'dot.streetwise.4': '•••• Especialista: Você conhece todos os jogadores e seus jogos.',
    'dot.streetwise.5': '••••• Mestre: As ruas são seu domínio.',

    'dot.subterfuge.1': '• Novato: Você pode contar mentirinhas.',
    'dot.subterfuge.2': '•• Praticante: Você pode manter uma história de cobertura.',
    'dot.subterfuge.3': '••• Competente: Você é um mentiroso e manipulador habilidoso.',
    'dot.subterfuge.4': '•••• Especialista: Você pode enganar quase qualquer um.',
    'dot.subterfuge.5': '••••• Mestre: Suas mentiras se tornam verdade.',

    // PERÍCIAS
    'dot.animalken.1': '• Novato: Você pode acariciar um cachorro.',
    'dot.animalken.2': '•• Praticante: Você pode treinar animais simples.',
    'dot.animalken.3': '••• Competente: Você tem jeito com todos os animais.',
    'dot.animalken.4': '•••• Especialista: Os animais confiam em você instintivamente.',
    'dot.animalken.5': '••••• Mestre: Você é um com as bestas.',

    'dot.crafts.1': '• Novato: Você pode fazer reparos básicos.',
    'dot.crafts.2': '•• Praticante: Você pode criar itens simples.',
    'dot.crafts.3': '••• Competente: Você é um artesão habilidoso.',
    'dot.crafts.4': '•••• Especialista: Seu trabalho é de qualidade profissional.',
    'dot.crafts.5': '••••• Mestre: Você cria obras-primas.',

    'dot.drive.1': '• Novato: Você tem carteira de motorista.',
    'dot.drive.2': '•• Praticante: Você pode dirigir em condições difíceis.',
    'dot.drive.3': '••• Competente: Você pode realizar manobras evasivas.',
    'dot.drive.4': '•••• Especialista: Você poderia ser um dublê.',
    'dot.drive.5': '••••• Mestre: Você é um com o veículo.',

    'dot.etiquette.1': '• Novato: Você conhece boas maneiras básicas.',
    'dot.etiquette.2': '•• Praticante: Você pode navegar situações sociais.',
    'dot.etiquette.3': '••• Competente: Você conhece todas as graças sociais.',
    'dot.etiquette.4': '•••• Especialista: Você é um mestre de protocolo.',
    'dot.etiquette.5': '••••• Mestre: Você define o padrão para a sociedade.',

    'dot.firearms.1': '• Novato: Você pode atirar com uma arma.',
    'dot.firearms.2': '•• Praticante: Você pode acertar um alvo confiavelmente.',
    'dot.firearms.3': '••• Competente: Você é um atirador habilidoso.',
    'dot.firearms.4': '•••• Especialista: Você raramente erra.',
    'dot.firearms.5': '••••• Mestre: Atirador lendário.',

    'dot.melee.1': '• Novato: Você pode balançar uma arma.',
    'dot.melee.2': '•• Praticante: Você sabe usar armas em combate.',
    'dot.melee.3': '••• Competente: Você é habilidoso com armas brancas.',
    'dot.melee.4': '•••• Especialista: Você é um mestre de armas.',
    'dot.melee.5': '••••• Mestre: Guerreiro lendário.',

    'dot.performance.1': '• Novato: Você pode cantar uma música.',
    'dot.performance.2': '•• Praticante: Você poderia se apresentar em locais locais.',
    'dot.performance.3': '••• Competente: Você é um artista profissional.',
    'dot.performance.4': '•••• Especialista: Você é famoso em sua área.',
    'dot.performance.5': '••••• Mestre: Artista lendário.',

    'dot.security.1': '• Novato: Você pode abrir uma fechadura simples.',
    'dot.security.2': '•• Praticante: Você pode contornar segurança básica.',
    'dot.security.3': '••• Competente: Você pode quebrar a maioria dos sistemas.',
    'dot.security.4': '•••• Especialista: Poucos sistemas podem te parar.',
    'dot.security.5': '••••• Mestre: Nenhuma fechadura pode te prender.',

    'dot.stealth.1': '• Novato: Você pode se esconder nas sombras.',
    'dot.stealth.2': '•• Praticante: Você pode se mover silenciosamente.',
    'dot.stealth.3': '••• Competente: Você é muito difícil de detectar.',
    'dot.stealth.4': '•••• Especialista: Você é um fantasma.',
    'dot.stealth.5': '••••• Mestre: Você é invisível.',

    'dot.survival.1': '• Novato: Você pode acampar.',
    'dot.survival.2': '•• Praticante: Você pode sobreviver na natureza.',
    'dot.survival.3': '••• Competente: Você prospera na natureza.',
    'dot.survival.4': '•••• Especialista: Você está em casa na selva.',
    'dot.survival.5': '••••• Mestre: A natureza se curva à sua vontade.',

    // CONHECIMENTOS
    'dot.academics.1': '• Novato: Ensino médio.',
    'dot.academics.2': '•• Praticante: Nível universitário.',
    'dot.academics.3': '••• Competente: Mestrado.',
    'dot.academics.4': '•••• Especialista: Nível de doutorado.',
    'dot.academics.5': '••••• Mestre: Acadêmico mundialmente renomado.',

    'dot.computer.1': '• Novato: Você pode usar email e navegar na web.',
    'dot.computer.2': '•• Praticante: Você pode resolver problemas.',
    'dot.computer.3': '••• Competente: Você é um programador habilidoso.',
    'dot.computer.4': '•••• Especialista: Você é um especialista em hacking.',
    'dot.computer.5': '••••• Mestre: Você é um deus digital.',

    'dot.finance.1': '• Novato: Você pode equilibrar um talão de cheques.',
    'dot.finance.2': '•• Praticante: Você entende investimentos.',
    'dot.finance.3': '••• Competente: Você poderia trabalhar em Wall Street.',
    'dot.finance.4': '•••• Especialista: Você manipula mercados.',
    'dot.finance.5': '••••• Mestre: Você controla economias.',

    'dot.investigation.1': '• Novato: Você pode encontrar pistas óbvias.',
    'dot.investigation.2': '•• Praticante: Você pode juntar evidências.',
    'dot.investigation.3': '••• Competente: Você é um detetive habilidoso.',
    'dot.investigation.4': '•••• Especialista: Você resolve o insolúvel.',
    'dot.investigation.5': '••••• Mestre: Nada permanece escondido de você.',

    'dot.law.1': '• Novato: Você conhece seus direitos básicos.',
    'dot.law.2': '•• Praticante: Você entende procedimentos legais.',
    'dot.law.3': '••• Competente: Você poderia advogar.',
    'dot.law.4': '•••• Especialista: Você é um especialista jurídico.',
    'dot.law.5': '••••• Mestre: Você molda a lei em si.',

    'dot.linguistics.1': '• Novato: Você fala um idioma adicional.',
    'dot.linguistics.2': '•• Praticante: Você fala dois idiomas adicionais.',
    'dot.linguistics.3': '••• Competente: Você fala quatro idiomas adicionais.',
    'dot.linguistics.4': '•••• Especialista: Você fala oito idiomas adicionais.',
    'dot.linguistics.5': '••••• Mestre: Você pode aprender qualquer idioma rapidamente.',

    'dot.medicine.1': '• Novato: Você sabe primeiros socorros.',
    'dot.medicine.2': '•• Praticante: Você poderia ser um enfermeiro.',
    'dot.medicine.3': '••• Competente: Você é um médico praticante.',
    'dot.medicine.4': '•••• Especialista: Você é um cirurgião renomado.',
    'dot.medicine.5': '••••• Mestre: Você realiza milagres médicos.',

    'dot.occult.1': '• Novato: Você conhece superstições básicas.',
    'dot.occult.2': '•• Praticante: Você entende tradições ocultas.',
    'dot.occult.3': '••• Competente: Você é versado no sobrenatural.',
    'dot.occult.4': '•••• Especialista: Você é um estudioso do oculto.',
    'dot.occult.5': '••••• Mestre: Você conhece os mistérios mais profundos.',

    'dot.politics.1': '• Novato: Você acompanha as notícias.',
    'dot.politics.2': '•• Praticante: Você entende sistemas políticos.',
    'dot.politics.3': '••• Competente: Você é politicamente conectado.',
    'dot.politics.4': '•••• Especialista: Você é um corretor de poder político.',
    'dot.politics.5': '••••• Mestre: Você controla governos.',

    'dot.science.1': '• Novato: Ciência do ensino médio.',
    'dot.science.2': '•• Praticante: Nível universitário.',
    'dot.science.3': '••• Competente: Você é um cientista profissional.',
    'dot.science.4': '•••• Especialista: Você faz descobertas revolucionárias.',
    'dot.science.5': '••••• Mestre: Você redefine a ciência em si.',

    // FORÇA DE VONTADE (1-10)
    'dot.willpower.1': '• Sem espinha: Você não tem determinação.',
    'dot.willpower.2': '•• Fraco: Você é facilmente influenciado.',
    'dot.willpower.3': '••• Sem determinação: Você prefere seguir do que liderar.',
    'dot.willpower.4': '•••• Tímido: Você duvida de sua própria força.',
    'dot.willpower.5': '••••• Seguro: Você tem um senso sólido de si mesmo.',
    'dot.willpower.6': '•••••• Confiante: Você confia em seu próprio julgamento.',
    'dot.willpower.7': '••••••• Determinado: Você raramente recua de um desafio.',
    'dot.willpower.8': '•••••••• Controlado: Você tem grande domínio sobre suas emoções.',
    'dot.willpower.9': '••••••••• Vontade de ferro: Sua determinação é lendária.',
    'dot.willpower.10': '•••••••••• Inabalável: Sua mente é uma fortaleza.',

    // HUMANIDADE (1-10)
    'dot.humanity.1': '• Monstruoso: Você é uma besta em forma humana.',
    'dot.humanity.2': '•• Bestial: Você tem muito pouco respeito pela vida.',
    'dot.humanity.3': '••• Frio: Você está desconectado das emoções humanas.',
    'dot.humanity.4': '•••• Insensível: Você está começando a perder o controle sobre a moralidade.',
    'dot.humanity.5': '••••• Distante: Você ainda se lembra do que é ser humano.',
    'dot.humanity.6': '•••••• Decente: Você tenta evitar danos desnecessários.',
    'dot.humanity.7': '••••••• Normal: A maioria dos humanos compartilha esse nível de moralidade.',
    'dot.humanity.8': '•••••••• Carinhoso: Você valoriza muito toda a vida.',
    'dot.humanity.9': '••••••••• Compassivo: Você é excepcionalmente moral.',
    'dot.humanity.10': '•••••••••• Santo: Você é um modelo de virtude.',

    // PARADA DE SANGUE (1-10)
    'dot.blood_pool.1': '• Sedento: Você quase não tem sangue. A fome é latente.',
    'dot.blood_pool.2': '•• Faminto: Sua besta está inquieta.',
    'dot.blood_pool.3': '••• Com fome: Você precisa se alimentar logo.',
    'dot.blood_pool.4': '•••• Neutro: Você pode funcionar normalmente.',
    'dot.blood_pool.5': '••••• Suficiente: Você tem sangue suficiente para tarefas menores.',
    'dot.blood_pool.6': '•••••• Satisfeito: Você se sente energizado.',
    'dot.blood_pool.7': '••••••• Cheio: Você está bem alimentado.',
    'dot.blood_pool.8': '•••••••• Abundante: Você tem uma abundância de vitae.',
    'dot.blood_pool.9': '••••••••• Transbordando: Você está pulsando com poder.',
    'dot.blood_pool.10': '•••••••••• Completo: Você está na capacidade máxima para sua geração.',

    // NÍVEIS DE DISCIPLINA (GENÉRICO)
    'dot.discipline.1': '• Nível 1 de Domínio',
    'dot.discipline.2': '•• Nível 2 de Domínio',
    'dot.discipline.3': '••• Nível 3 de Domínio',
    'dot.discipline.4': '•••• Nível 4 de Domínio',
    'dot.discipline.5': '••••• Nível 5 de Domínio',
};

